# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-ISO8601
version:      0.001
version_from: lib/Date/ISO8601.pm
installdirs:  site
requires:
    Math::BigInt:                  1.64
    Math::BigRat:                  0.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
